guid = "25f1670b-3be3-4f75-aacc-3b5390d355a0"
[settings]
project_name = "Unity Mono"
version_control = "Git"
branch = "master"
git_repository_url = "https://github.com/Mainframe-Games/mg-ci.git?path=/TestProjects/UnityMono"
game_engine = "Unity"
store_url = "https://"
store_thumbnail_url = "https://"
last_successful_build = "0"
[prebuild]
build_number_standalone = true
build_number_iphone = false
android_version_code = false
[[build_targets]]
name = "Windows"
extension = ".exe"
product_name = "Unity Mono"
target = "StandaloneWindows64"
target_group = "Standalone"
sub_target = "Player"
build_path = "Builds/Windows"
build_options = 0
[[build_targets]]
name = "Mac"
extension = ".app"
product_name = "Unity Mono"
target = "StandaloneOSX"
target_group = "Standalone"
sub_target = "Player"
build_path = "Builds/Mac"
build_options = 0
[[build_targets]]
name = "Linux"
extension = ".x86_64"
product_name = "Unity Mono"
target = "StandaloneLinux64"
target_group = "Standalone"
sub_target = "Player"
build_path = "Builds/Linux"
build_options = 0
[deployment]
apple_store = false
google_store = false
clanforge = false
aws_s3 = false
